services:
  - type: web
    name: ask-me-chatbot
    env: python
    plan: free               # change if you use a paid plan
    region: oregon           # or frankfurt/singapore etc.

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: gunicorn ask_me.wsgi:application

    envVars:
      - key: SECRET_KEY
        generateValue: true          # Render will auto-generate a secure key

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: "127.0.0.1,localhost,.onrender.com"

      - key: TIME_ZONE
        value: "Asia/Kolkata"

      # Optional: only if you use it in code
      - key: GROQ_API_KEY
        sync: false                  # set value manually in dashboard later

      # Optional: only for Windows local, keep empty on Render
      - key: PYTESSERACT_CMD
        value: ""
